name: TBF Track

on:
  workflow_dispatch:

jobs:
  check-duyurular:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Libs
        run: pip install requests beautifulsoup4

      - name: Load cache
        uses: actions/cache@v4
        with:
          path: seen_posts.json
          key: seen-posts-cache
          restore-keys: seen-posts-cache

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tbf_bot.py

      - name: Save announcements
        uses: actions/cache@v4
        with:
          path: seen_posts.json
          key: seen-posts-cache-${{ github.run_id }}
